// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxbnnbdjyrilusqywghc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4Ym5uYmRqeXJpbHVzcXl3Z2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTY0MzgsImV4cCI6MjA2ODA3MjQzOH0.AeTi_yjW7AIoj8eqnmXwr2nWt9HZGKHWOYYKKS6f3SU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});